In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv
import warnings
import os

warnings.simplefilter(action="ignore", category=FutureWarning)
warnings.simplefilter(action="ignore", category=UserWarning)
warnings.simplefilter("ignore", pd.errors.SettingWithCopyWarning)

In [4]:
folder = os.fsencode("data/football")
dataframes = []
for file in sorted(os.listdir(folder)):
    filename = os.fsdecode(file)
    if filename.endswith(".csv"):
        df = pd.read_csv("data/football/" + filename)
        dataframes.append(df)

data = pd.concat(dataframes, axis=0)

In [6]:
data = data[[
    "Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "FTR",
    "B365H", "B365D", "B365A", "AvgH", "AvgD", "AvgA", 
    "B365>2.5", "B365<2.5", "Avg>2.5", "Avg<2.5"
]]

In [8]:
data.describe()

,FTHG,FTAG,B365H,B365D,B365A,AvgH,AvgD,AvgA,B365>2.5,B365<2.5,Avg>2.5,Avg<2.5
count,3680.000000,3680.000000,3677.000000,3677.000000,3677.000000,2539.000000,2539.000000,2539.000000,2536.000000,2536.000000,2538.000000,2538.000000
mean,1.487228,1.265217,2.859989,3.999551,4.441634,2.831075,3.951445,4.217507,1.881573,2.030434,1.872975,2.029200
std,1.257043,1.157970,1.875993,1.052519,3.447641,1.678056,0.921750,3.015633,0.286984,0.361413,0.280304,0.352685
min,0.000000,0.000000,1.060000,2.400000,1.160000,1.100000,2.740000,1.170000,1.250000,1.400000,1.260000,1.410000
25%,1.000000,0.000000,1.620000,3.300000,2.200000,1.680000,3.350000,2.200000,1.660000,1.730000,1.660000,1.770000
50%,1.000000,1.000000,2.250000,3.600000,3.250000,2.310000,3.640000,3.210000,1.885000,2.000000,1.850000,1.970000
75%,2.000000,2.000000,3.400000,4.330000,5.500000,3.370000,4.230000,5.055000,2.080000,2.200000,2.060000,2.220000
max,8.000000,7.000000,17.000000,15.000000,34.000000,16.810000,10.060000,25.090000,3.000000,4.000000,2.860000,3.790000

In [11]:
data["1x2margin"] = (1/data["B365H"]) + (1/data["B365D"]) + (1/data["B365A"])

In [13]:
data.describe()

,FTHG,FTAG,B365H,B365D,B365A,AvgH,AvgD,AvgA,B365>2.5,B365<2.5,Avg>2.5,Avg<2.5,1x2margin
count,3680.000000,3680.000000,3677.000000,3677.000000,3677.000000,2539.000000,2539.000000,2539.000000,2536.000000,2536.000000,2538.000000,2538.000000,3677.000000
mean,1.487228,1.265217,2.859989,3.999551,4.441634,2.831075,3.951445,4.217507,1.881573,2.030434,1.872975,2.029200,1.053959
std,1.257043,1.157970,1.875993,1.052519,3.447641,1.678056,0.921750,3.015633,0.286984,0.361413,0.280304,0.352685,0.005917
min,0.000000,0.000000,1.060000,2.400000,1.160000,1.100000,2.740000,1.170000,1.250000,1.400000,1.260000,1.410000,1.026255
25%,1.000000,0.000000,1.620000,3.300000,2.200000,1.680000,3.350000,2.200000,1.660000,1.730000,1.660000,1.770000,1.050000
50%,1.000000,1.000000,2.250000,3.600000,3.250000,2.310000,3.640000,3.210000,1.885000,2.000000,1.850000,1.970000,1.053426
75%,2.000000,2.000000,3.400000,4.330000,5.500000,3.370000,4.230000,5.055000,2.080000,2.200000,2.060000,2.220000,1.057202
max,8.000000,7.000000,17.000000,15.000000,34.000000,16.810000,10.060000,25.090000,3.000000,4.000000,2.860000,3.790000,1.085413

In [15]:
data["OUmargin"] = (1/data["B365>2.5"]) + (1/data["B365<2.5"])

In [17]:
data.describe()

,FTHG,FTAG,B365H,B365D,B365A,AvgH,AvgD,AvgA,B365>2.5,B365<2.5,Avg>2.5,Avg<2.5,1x2margin,OUmargin
count,3680.000000,3680.000000,3677.000000,3677.000000,3677.000000,2539.000000,2539.000000,2539.000000,2536.000000,2536.000000,2538.000000,2538.000000,3677.000000,2536.000000
mean,1.487228,1.265217,2.859989,3.999551,4.441634,2.831075,3.951445,4.217507,1.881573,2.030434,1.872975,2.029200,1.053959,1.050146
std,1.257043,1.157970,1.875993,1.052519,3.447641,1.678056,0.921750,3.015633,0.286984,0.361413,0.280304,0.352685,0.005917,0.011488
min,0.000000,0.000000,1.060000,2.400000,1.160000,1.100000,2.740000,1.170000,1.250000,1.400000,1.260000,1.410000,1.026255,1.017818
25%,1.000000,0.000000,1.620000,3.300000,2.200000,1.680000,3.350000,2.200000,1.660000,1.730000,1.660000,1.770000,1.050000,1.048346
50%,1.000000,1.000000,2.250000,3.600000,3.250000,2.310000,3.640000,3.210000,1.885000,2.000000,1.850000,1.970000,1.053426,1.054225
75%,2.000000,2.000000,3.400000,4.330000,5.500000,3.370000,4.230000,5.055000,2.080000,2.200000,2.060000,2.220000,1.057202,1.057111
max,8.000000,7.000000,17.000000,15.000000,34.000000,16.810000,10.060000,25.090000,3.000000,4.000000,2.860000,3.790000,1.085413,1.084629